-- Insert Swadesh vocabulary for major languages
INSERT INTO kosakata (bahasa_id, kata, arti_indonesia, fonetik_ipa)
SELECT id, 'siji', 'satu', '/si.dʒi/' FROM bahasa WHERE nama_bahasa = 'Jawa'
UNION ALL SELECT id, 'loro', 'dua', '/lo.ro/' FROM bahasa WHERE nama_bahasa = 'Jawa'
UNION ALL SELECT id, 'telu', 'tiga', '/tə.lu/' FROM bahasa WHERE nama_bahasa = 'Jawa'
UNION ALL SELECT id, 'papat', 'empat', '/pa.pat/' FROM bahasa WHERE nama_bahasa = 'Jawa'
UNION ALL SELECT id, 'lima', 'lima', '/li.ma/' FROM bahasa WHERE nama_bahasa = 'Jawa'
UNION ALL SELECT id, 'nelu', 'enam', '/ne.lu/' FROM bahasa WHERE nama_bahasa = 'Jawa'
UNION ALL SELECT id, 'pitu', 'tujuh', '/pi.tu/' FROM bahasa WHERE nama_bahasa = 'Jawa'
UNION ALL SELECT id, 'wolung', 'delapan', '/wo.luŋ/' FROM bahasa WHERE nama_bahasa = 'Jawa'
UNION ALL SELECT id, 'sanga', 'sembilan', '/sa.ŋa/' FROM bahasa WHERE nama_bahasa = 'Jawa'
UNION ALL SELECT id, 'sepuluh', 'sepuluh', '/se.puh/' FROM bahasa WHERE nama_bahasa = 'Jawa'
UNION ALL SELECT id, 'hiji', 'satu', '/hi.dʒi/' FROM bahasa WHERE nama_bahasa = 'Sunda'
UNION ALL SELECT id, 'dua', 'dua', '/du.a/' FROM bahasa WHERE nama_bahasa = 'Sunda'
UNION ALL SELECT id, 'tilu', 'tiga', '/ti.lu/' FROM bahasa WHERE nama_bahasa = 'Sunda'
UNION ALL SELECT id, 'opat', 'empat', '/o.pat/' FROM bahasa WHERE nama_bahasa = 'Sunda'
UNION ALL SELECT id, 'limo', 'lima', '/li.mo/' FROM bahasa WHERE nama_bahasa = 'Sunda'
UNION ALL SELECT id, 'genep', 'enam', '/gə.nəp/' FROM bahasa WHERE nama_bahasa = 'Sunda'
UNION ALL SELECT id, 'pitu', 'tujuh', '/pi.tu/' FROM bahasa WHERE nama_bahasa = 'Sunda'
UNION ALL SELECT id, 'waliku', 'delapan', '/wa.li.ku/' FROM bahasa WHERE nama_bahasa = 'Sunda'
UNION ALL SELECT id, 'salapan', 'sembilan', '/sa.la.pan/' FROM bahasa WHERE nama_bahasa = 'Sunda'
UNION ALL SELECT id, 'sapuluah', 'sepuluh', '/sa.pu.lu.a/' FROM bahasa WHERE nama_bahasa = 'Sunda'
UNION ALL SELECT id, 'seppu', 'satu', '/sep.ru/' FROM bahasa WHERE nama_bahasa = 'Bugis'
UNION ALL SELECT id, 'dua', 'dua', '/du.a/' FROM bahasa WHERE nama_bahasa = 'Bugis'
UNION ALL SELECT id, 'telu', 'tiga', '/tə.lu/' FROM bahasa WHERE nama_bahasa = 'Bugis'
UNION ALL SELECT id, 'pannang', 'empat', '/pan.an/' FROM bahasa WHERE nama_bahasa = 'Bugis'
UNION ALL SELECT id, 'limmuru', 'lima', '/lim.ru.ru/' FROM bahasa WHERE nama_bahasa = 'Bugis'
UNION ALL SELECT id, 'rompu', 'enam', '/rom.ru/' FROM bahasa WHERE nama_bahasa = 'Bugis'
UNION ALL SELECT id, 'pito', 'tujuh', '/pi.to/' FROM bahasa WHERE nama_bahasa = 'Bugis'
UNION ALL SELECT id, 'toloppu', 'delapan', '/to.lo.pru/' FROM bahasa WHERE nama_bahasa = 'Bugis'
UNION ALL SELECT id, 'sappulo', 'sembilan', '/sap.ru.lo/' FROM bahasa WHERE nama_bahasa = 'Bugis'
UNION ALL SELECT id, 'polo', 'sepuluh', '/po.lo/' FROM bahasa WHERE nama_bahasa = 'Bugis'
ON CONFLICT DO NOTHING;
