-- Enrich wilayah and provinsi from dapobas data

UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Abai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Abrap' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Abui (Aboa)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Abun' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Abun Gii  (Abun Jii)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Abun Ji  (Karon Pantai)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Aceh' WHERE nama_bahasa = 'Aceh' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Adagum (Citak Wagabus)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Adang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Afilaup' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Aframa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Air Matoa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Airo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Airoran' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ale' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Alor' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Alune' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Amathamit' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ambai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Ambalau' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Ambel' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Amber' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Amungkal' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Anakalang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Anasi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ansus-Papuma' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Anus' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Aoheng (Penihing)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Arakam' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Arandai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Are' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Arguni (Taver)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Armati Sarma' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Arubos' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Arui-Mor' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'As' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Asmat Bets Mbup' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Asmat Safan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Asmat Sawa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Asmat Sirat' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Asmat Unir Sirau' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Asmat Waijens' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Atam (Temma)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Auye' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Awban' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Awe (Maweyo, Kaburi)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Awera' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Awyu Anggai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Awyu Darat Kotiak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Awyu Darat Yagatsu-Kiki' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Awyu Laut' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Awyu Meto' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Awyu Tokompatu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Bacan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Bada' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Baedate' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Baham' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Bahau Diaq Lay' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Bahau Ujoh Bilang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Bajau Pondong' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Selatan' WHERE nama_bahasa = 'Bajau Semayap' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Jambi' WHERE nama_bahasa = 'Bajau Tungkal Satu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Jawa dan Bali, Sulawesi, Nusa Tenggara Barat, Nusa Tenggara Timur, Maluku', provinsi = 'Jawa Timur,  Sulawesi Tengah,  Sulawesi Selatan,  Sulawesi Tenggara,  Gorontalo,  Nusa Tenggara Barat,  Nusa Tenggara Timur,  Maluku Utara' WHERE nama_bahasa = 'Bajo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Bajo Delang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Barat' WHERE nama_bahasa = 'Bakatik' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah,  Kalimantan Selatan' WHERE nama_bahasa = 'Bakumpai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Balaesang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Balai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Balantak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra, Jawa dan Bali, Kalimantan, Sulawesi, Nusa Tenggara Barat', provinsi = 'Lampung,  Bali,  Kalimantan Tengah,  Sulawesi Tenggara,  Nusa Tenggara Barat' WHERE nama_bahasa = 'Bali' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Balkewan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Banda' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Banggai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra, Kalimantan', provinsi = 'Riau,  Jambi,  Kalimantan Tengah,  Kalimantan Selatan' WHERE nama_bahasa = 'Banjar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Utara' WHERE nama_bahasa = 'Bantik' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Barakai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Barapasi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Barat' WHERE nama_bahasa = 'Baras' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Basap' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Lampung' WHERE nama_bahasa = 'Basemah' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Aceh,  Sumatra Utara,  Sumatra Barat,  Riau' WHERE nama_bahasa = 'Batak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Batanta' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Batero' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Batu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Batuley' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Bauzi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Bawija' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Bayan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Bedoanas (Baruan-Erokwanas)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Beneraf' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Barat' WHERE nama_bahasa = 'Benggaulu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Bengkulu' WHERE nama_bahasa = 'Bengkulu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Benuaq' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Selatan' WHERE nama_bahasa = 'Berangas' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Berbai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Berik' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Beser' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Beser Swaimbon' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Besoa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Beyaboa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Biak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Bian Marind Deg' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Barat', provinsi = 'Nusa Tenggara Barat' WHERE nama_bahasa = 'Bima (Mbojo)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Biritai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Biyekwok' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Bku (Bgu)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Blagar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Blue Klesi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Bobar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Boi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Boing' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Utara' WHERE nama_bahasa = 'Bolaang Mongondow (Bolmong)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Selatan' WHERE nama_bahasa = 'Bonerate' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Bonoi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Bora-Bora' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Bouram' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Buagani' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Barat' WHERE nama_bahasa = 'Budong-Budong (Tangkou)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra, Jawa dan Bali, Kalimantan, Sulawesi, Nusa Tenggara Barat', provinsi = 'Riau,  Jambi,  Lampung,  DKI Jakarta,  Kalimantan Selatan,  Kalimantan Timur,  Kalimantan Utara,  Sulawesi Tengah,  Sulawesi Selatan,  Nusa Tenggara Barat' WHERE nama_bahasa = 'Bugis' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Selatan' WHERE nama_bahasa = 'Bugis De' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Barat' WHERE nama_bahasa = 'Bukat' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Buli' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Bulungan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Buna (Bunak)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Bungku' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Buol' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Burate' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Buru' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Burukmakot' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Burumeso' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Busami' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tenggara' WHERE nama_bahasa = 'Cia-Cia' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Citak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tenggara' WHERE nama_bahasa = 'Culambacu (Tulambatu)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dabe' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dabra' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Daikat' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dajub' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Damal' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Damar Timur' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Damban  (Ndamban)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dani' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dani Atas' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dani Bawah' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dani Bokondini' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dani Tengah' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Daranto (Deranto)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dasigo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Dawan (Timor)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Dawelor' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Dayak Bara Injey' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Dayak Baream' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Dayak Kapuas' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Dayak Ngaju' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Dayak Pulau Telo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Dayak Sei Dusun' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Deing' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dem' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Demisa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Aceh' WHERE nama_bahasa = 'Devayan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Diae' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dinana' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dintere' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Diuwe' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Dobel' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Dondo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dra' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Dubu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Dulolong' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Dusner  (Usner)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Dusun' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Selatan' WHERE nama_bahasa = 'Dusun Deyah' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Dusun Kalahien' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Duvle' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Efpan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Eik (Foau)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Eipumek' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ekari' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Elnama' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Elseng' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Elseng Koarjap' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Emem (Emumu)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Emplawas' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Bengkulu' WHERE nama_bahasa = 'Enggano' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Engkalembu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Esaro  (Kawit)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Etik (Barto,Maria)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Fakafuku' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Fayu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Fermanggem' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Fkour' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Fokri (Hokli)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Fordata (Iyaru)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Galela' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Barat' WHERE nama_bahasa = 'Galik (Golik)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Gane' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Gaura' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Aceh' WHERE nama_bahasa = 'Gayo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Girimora' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Gorap' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Utara,  Gorontalo' WHERE nama_bahasa = 'Gorontalo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Gua' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Gufinti' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Hamap' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Hatam' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Hatam Mole' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Helong' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Hewa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Hitu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Hoti' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Hubla' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Iau' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Ibu (Ibo)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Iha' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Illiun (Il’iiuun)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Imbuti  (Marind)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Imiyan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Inanwatan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Inora' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Intamaja' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Irarutu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Irarutu Bofuer' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Irawa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Irires' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Isirawa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Jair' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Jamor' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra, Jawa dan Bali, Kalimantan, Sulawesi, Nusa Tenggara Barat', provinsi = 'Aceh,  Sumatra Utara,  Jambi,  Sumatra Selatan,  Bengkulu,  Lampung,  Jawa Barat,  Jawa Tengah,  Daerah Istimewa Yogyakarta,  Jawa Timur,  Banten,  Bali,  Kalimantan Selatan,  Kalimantan Timur,  Sulawesi Tenggara,  Nusa Tenggara Barat' WHERE nama_bahasa = 'Jawa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Jelako' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Jinak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Joerat' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Jorop' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Juvutek' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kabola' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Kadai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kadi (Muyu Utara)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Kadorih' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kaera' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kafoa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Kaham' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Kaiely' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kaigar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Kaili' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Kais' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kaiya (Kaiy)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Kalabra' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Kalamang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kalela (Kawela)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kamang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kambera' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kambera Pandawai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Kamberau (Bauana)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Kambran' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kamindip' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kamoro' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kanum Barkari' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kapayap (Soko Benanu)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kapori (Kapauri)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kaptiau (Kapitiau)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Karas' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Karey' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Karon' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Karufo Auf' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Katingan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kaureh' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kawera' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kawiyet' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Barat' WHERE nama_bahasa = 'Kayaan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kayo Pulau' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Sumatra Selatan,  Kepulauan Bangka Belitung' WHERE nama_bahasa = 'Kayu Agung' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kedang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Kei' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kejer Manirem' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kekawia' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kemak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Kemberano' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kemtuk' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur,  Kalimantan Utara' WHERE nama_bahasa = 'Kenyah' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kenyam Niknene' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Jambi' WHERE nama_bahasa = 'Kerinci' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ketengban' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Keuw' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kimaam' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kimagima' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kimki' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kimyal' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kiraman' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kiri-Kiri' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kitum' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kiwai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Klamu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Klesi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Klon' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Klufo (Krowai Rawa, Krowai Umum)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kodi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kofey' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Koiwai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Kokoda' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Kola' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kolana' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kombai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kombai Kali  (Tajan)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Komela' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Sumatra Selatan' WHERE nama_bahasa = 'Komering' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Komodo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Komolom  (Mombun)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Kompane' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Komyandaret' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Barat' WHERE nama_bahasa = 'Kone-Konee' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Konerau' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Selatan' WHERE nama_bahasa = 'Konjo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kopkaka' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kopkaka Seredela (Kopkaga Seredela)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Korowai Baigun  (Atigun)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Korowai Karuwage (Korowage)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Korowai Selatan (Korowai Lumpur/Klufwo Auf Umbale)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kui' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Kulatera' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Kulawi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tenggara' WHERE nama_bahasa = 'Kulisusu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Kur' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Kuri  (Nabi)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kurudu (Myobo)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kwari' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kwer (Kofet/Kwet)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kwerba' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kwesten Arare' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Kwinsu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Labala' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Selatan' WHERE nama_bahasa = 'Laiyolo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Lamaholot' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Lamatuka' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Lamboya' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Lampung' WHERE nama_bahasa = 'Lampung' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Jawa dan Bali', provinsi = 'Banten' WHERE nama_bahasa = 'Lampung Cikoneng' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Lani' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tenggara' WHERE nama_bahasa = 'Lasalimu-Kamaru' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Lauje Malala' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah,  Kalimantan Selatan' WHERE nama_bahasa = 'Lawangan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Leinam' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Sumatra Selatan' WHERE nama_bahasa = 'Lematang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Selatan' WHERE nama_bahasa = 'Lemolang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Lepki' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Letti' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Lewuka' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Liki' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Lio' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Lola' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Lona' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Long Pulung' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Loon' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Luhu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Lundayeh' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Lura' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah,  Kalimantan Selatan' WHERE nama_bahasa = 'Maanyan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Jawa dan Bali, Nusa Tenggara Barat', provinsi = 'Jawa Timur,  Bali,  Nusa Tenggara Barat' WHERE nama_bahasa = 'Madura' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Maibrat' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Mairasi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Maisomara' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi, Nusa Tenggara Barat', provinsi = 'Sulawesi Selatan,  Nusa Tenggara Barat' WHERE nama_bahasa = 'Makassar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Makatian' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Makean Dalam' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Makean Luar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Makleu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Barat' WHERE nama_bahasa = 'Mamasa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Mambora' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Barat' WHERE nama_bahasa = 'Mamuju' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Selatan,  Sulawesi Barat' WHERE nama_bahasa = 'Mandar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Barat', provinsi = 'Nusa Tenggara Barat' WHERE nama_bahasa = 'Mandarin Ampenan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Jawa dan Bali', provinsi = 'DKI Jakarta' WHERE nama_bahasa = 'Mandarin DKI Jakarta' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Mander' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Mandobo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Mandobo Bawah' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Mandobo Tengah (Kop Kambo)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Manem' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Manggarai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Mansim Borai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Manua  (Eritai)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Manulea' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Marap' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Maraw' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Mare' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Marita' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Marlasi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Marori  (Morori)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Marsela Barat (Masela Barat)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Marsela Tengah (Masela Tengah)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Marsela Timur (Masela Timur)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Masarete' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Masep' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Masimasi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Selatan' WHERE nama_bahasa = 'Massenrengpulu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Matbat' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Matlow' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Mawes Dey (Mawesdey)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Mawes Wares (Maweswares)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Maya Legenyan-Kawei' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Mee Ugia' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Mee Wosokuno' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Mek Kosarek' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Mek Naica' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Mek Nipsan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra, Jawa dan Bali, Kalimantan, Sulawesi, Nusa Tenggara Barat, Nusa Tenggara Timur, Maluku, Papua', provinsi = 'Sumatra Utara,  Riau,  Jambi,  Sumatra Selatan,  Kepulauan Bangka Belitung,  DKI Jakarta,  Bali,  Kalimantan Barat,  Kalimantan Tengah,  Kalimantan Timur,  Sulawesi Utara,  Nusa Tenggara Barat,  Nusa Tenggara Timur,  Maluku,  Maluku Utara,  Papua,  Kepulauan Riau' WHERE nama_bahasa = 'Melayu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Sumatra Barat' WHERE nama_bahasa = 'Mentawai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Mentaya' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Meyah' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Miere' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Utara,  Gorontalo' WHERE nama_bahasa = 'Minahasa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Utara' WHERE nama_bahasa = 'Minahasa Tonsawang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Utara' WHERE nama_bahasa = 'Minahasa Tonsea' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Aceh,  Sumatra Utara,  Sumatra Barat,  Riau,  Jambi,  Bengkulu' WHERE nama_bahasa = 'Minangkabau' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Mnanggi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Moa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Modole' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Moi Maniwo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Moi Sigin' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Molof' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Momuna' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Moni Bibida' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Moni-Kegouda' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Monuna Samboga' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Mooi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Mor' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Moraid' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tenggara' WHERE nama_bahasa = 'Morunene (Moronene)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Moskona' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Motu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Mpur' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Mpur Pantai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tenggara' WHERE nama_bahasa = 'Muna' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Munggui' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Muri (Mer)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Murkim' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Muyu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Muyu Selatan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Nafri' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Nage' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Nagi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Nai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Nalik Selatan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Namak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Namalu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Namas' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Namblong' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Namla' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Namut' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Napiti' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Napiti Pantai-Busama (Napiti Pantai)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Narau' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Nare' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Naulu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Ndao' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ndarame' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ndauwa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ndom' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Ndora' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Nedebang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Ngada' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ngalum' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Nggem' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ngguntar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ngkalembu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Sumatra Utara' WHERE nama_bahasa = 'Nias' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Nila' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ningrum' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Nobuk (Kwerba)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Nosaudare' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Nubuai-Waren' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Numfor (Mansinam)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Nyaw' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Obokuitai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Oedate (Kerema)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Sumatra Selatan' WHERE nama_bahasa = 'Ogan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Oirata' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Okpari' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Omesuri' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ormu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Oroyliye' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Orya' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Palamul' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Palu e' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Pamona' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Barat' WHERE nama_bahasa = 'Pannei' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Utara' WHERE nama_bahasa = 'Pasan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Pasir (Paser)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Patani' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Sumatra Selatan' WHERE nama_bahasa = 'Pedamaran' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Pembuang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Pigapu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Pijin' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Piliana' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Pipikoro' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Piru' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Pokoro' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Utara' WHERE nama_bahasa = 'Ponosakan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tenggara' WHERE nama_bahasa = 'Pulo (Wakatobi)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Barat' WHERE nama_bahasa = 'Punan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Punan Long Lamcin' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Punan Merah' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Punan Paking' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Pupis' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Pura' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Puragi-Saga' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Raijua' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Selatan' WHERE nama_bahasa = 'Rampi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Rarankwa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Bengkulu' WHERE nama_bahasa = 'Rejang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Retta' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Riantana' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Barat' WHERE nama_bahasa = 'Ribun (Rihun)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Riung' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ro (Ru)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Ron' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Rongga' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Roswar (Saref)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Rote' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Sabakor (Buruwai)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Saban' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Sabu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sagapu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Sahu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Salafen Matbat' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Salas' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Saleman' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Salkma' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Saluan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Saman' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Samasuru' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Samate' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Selatan' WHERE nama_bahasa = 'Samihin' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Sampit' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Utara,  Sulawesi Tengah' WHERE nama_bahasa = 'Sangihe Talaud (Satal)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Saponi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Sar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi, Nusa Tenggara Barat', provinsi = 'Sulawesi Tenggara,  Nusa Tenggara Barat' WHERE nama_bahasa = 'Sasak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Jawa dan Bali', provinsi = 'Bali' WHERE nama_bahasa = 'Sasak Bali' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sasawa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Saurisirami' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sause-Ures (Barazre)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Sawai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Saweru' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sawi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Sawila' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'See' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Segaai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Segar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Seget' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Sekar-Onim' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah,  Sulawesi Selatan' WHERE nama_bahasa = 'Seko' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Selaru' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Selegof' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Seluwarsa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sempan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Senggi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sentani' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Seram' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Serili' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Serua' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Serui Laut' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Aceh' WHERE nama_bahasa = 'Sigulai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sikari' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Sikka' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Silimo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sipisi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Skou' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Smarki Kanum' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'So a' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Soba' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sobey' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sobey Wakde' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Somu (Toro)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Soon' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sorabi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Sou' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Sough (Manikion)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Sough Bohon' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sowiwa (Morowa)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Soytai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Srum' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sudate (Sehudate)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Sula' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Sumba Barat' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Barat', provinsi = 'Nusa Tenggara Barat' WHERE nama_bahasa = 'Sumbawa (Samawa)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sumuri (Sumuri)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra, Jawa dan Bali, Sulawesi', provinsi = 'Bengkulu,  Lampung,  DKI Jakarta,  Jawa Barat,  Jawa Tengah,  Banten,  Sulawesi Tenggara' WHERE nama_bahasa = 'Sunda' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sunum' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Taa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tabahair (Bipim, Bipin)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tabla' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Tabundung' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Tagalisa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Taliabu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tamakuri' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Barat' WHERE nama_bahasa = 'Taman' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tamer Tunai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Tamuan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Tandia' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tangko' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tapea' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Tarangan Barat' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Tarangan Timur' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tarfia' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tause' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Tawoyan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tawu Ane' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tebako' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tefanma' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tefaro (Demba)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Tehit' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Tehit Dit (Tehit Tua)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Teiwa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Telaah Babar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Telepe' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Tenggalan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Teon' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Tepin' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Ternate' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Tetun' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tevera Pew' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Tewa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Tidung' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tobati' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Tobelo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tenggara' WHERE nama_bahasa = 'Tolaki' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Tombatu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tomor' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Barat' WHERE nama_bahasa = 'Topoiyo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Selatan' WHERE nama_bahasa = 'Toraja' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Torweja' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Totoberi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Totoli' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Towe' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Trimuris-Bagusa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tsaukwambo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Tunjung' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ulakin (Ulakuno)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Uma Lung' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Una' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Ure (Mere)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Uruangnirin' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Barat,  Kalimantan Tengah' WHERE nama_bahasa = 'Uud Danum (Ot Danum)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Vamin' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Vedan Nus (Podena)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wabo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Waicen' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wairate (Debra)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Walak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Waliam' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Walsa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wambo Tawe Tirop' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wambon Kenondik (Wombon, Womsi)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Wamesa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Wandamen' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wanggom' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wano' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Wanukaka (Wanokaka)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Warari Onate' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Wardo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Warembori' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wari' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Warlon' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Warry' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Waruri (Ambumi)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wate' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Wau Arak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Weinami' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Wemale' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Wersing (Kolana (Wirasina))' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Wewewa (Wejewa)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Windesi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wiyagar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Woda-Woda' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wolani' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tenggara' WHERE nama_bahasa = 'Wolio' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wombon (Womsi)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wonti (Waropen)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wooi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Woria' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Selatan' WHERE nama_bahasa = 'Wotu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yabanda (Away)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yabega' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Yaben' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yafi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yaghai Mur' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yaghai Wairu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Yahadian-Mugim' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yakapis' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Yalahatan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yali Anggruk' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yali Kosarek' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yali Ninia' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yali Pass Valley' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yamas' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Yamueti' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Yatoke' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yaur' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yaur Rihegure' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yawa Onate' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yei' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yei Bawah' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yelmek' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yeresiam' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Yeresiam Kiruru' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Yeresiam Pedalaman (Sirise)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yeretuar (Umare)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yetfa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yokari' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yoke' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yonggom' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Yuafeta' AND (wilayah IS NULL OR provinsi IS NULL);
