UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Punan Merah') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Sahu') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Tehit') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Tenggalan') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Totoli') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Yamdena dialek') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Bekak') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Lematang') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Terancam Punah' WHERE LOWER(nama_bahasa) = LOWER('kategori kris') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Adang') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Arguni') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Bajau Tungkal Satu') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Bku') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Dubu') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Yamdena dialek') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Irarutu') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Kalabra') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Konjo') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Makleu') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Mander') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Minahasa') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Namla') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Nedebang') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Podena') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Ponosakan') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Samasuru') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Sangihe Talaud') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Sawai') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Tunjung') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Punah' WHERE LOWER(nama_bahasa) = LOWER('Enggano') AND (status_vitalitas IS NULL OR status_vitalitas = '');
