UPDATE bahasa SET status_vitalitas = 'Rentan' WHERE LOWER(nama_bahasa) = LOWER('Meoswar') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Rentan' WHERE LOWER(nama_bahasa) = LOWER('Minahasa') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Rentan' WHERE LOWER(nama_bahasa) = LOWER('Melayu dialek') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Rongga') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Senggi') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Somu') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Wolio') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Lampung') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Modole') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Marori') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Seget') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Buru') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Gorontalo dialek') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Hatam') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Hitu') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Lemolang') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Melayu di Indragiri') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Ogan') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Rampi') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Saleman') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Toba') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Yalahatan') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Dra') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Karas') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Massenrengpulu') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Mentawai') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Ngguntar') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Nias') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Pannei') AND (status_vitalitas IS NULL OR status_vitalitas = '');
UPDATE bahasa SET status_vitalitas = 'Mengalami Kemunduran' WHERE LOWER(nama_bahasa) = LOWER('Pedamaran') AND (status_vitalitas IS NULL OR status_vitalitas = '');
