-- Enrich wilayah and provinsi from petabahsa data

UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Aabinomin' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Abai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Abrap' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Abui (Aboa)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Abun' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Abun Gii  (Abun Jii)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Abun Ji  (Karon Pantai)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Aceh' WHERE nama_bahasa = 'Aceh' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Adagum (Citak Wagabus)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Adang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Afilaup' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Aframa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Air Matoa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Airo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Airoran' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ale' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Alor' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Alune' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Amathamit' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ambai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Ambalau' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Ambel' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Amber' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Amungkal' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Anakalang' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Anasi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ansus-Papuma' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Anus' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Aoheng (Penihing)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Arakam' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Arandai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Are' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Arguni (Taver)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Armati Sarma' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Arubos' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Arui-Mor' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'As' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Asmat Bets Mbup' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Asmat Safan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Asmat Sawa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'See' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Segaai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Segar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Seget' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Sekar-Onim' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah, Sulawesi Selatan' WHERE nama_bahasa = 'Seko' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Selaru' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Selegof' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Seluwarsa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sempan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Senggi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sentani' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Seram' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Serili' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Serua' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Serui Laut' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Aceh' WHERE nama_bahasa = 'Sigulai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sikari' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Sikka' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Silimo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sipisi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Skou' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Smarki Kanum' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'So a' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Soba' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sobey' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sobey Wakde' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Somu (Toro)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Soon' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sorabi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Sou' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Sough (Manikion)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Sough Bohon' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sowiwa (Morowa)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Soytai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Srum' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sudate (Sehudate)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Sula' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Sumba Barat' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Barat', provinsi = 'Nusa Tenggara Barat' WHERE nama_bahasa = 'Sumbawa (Samawa)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sumuri (Sumuri)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sumatra', provinsi = 'Bengkulu, Lampung, DKI Jakarta, Jawa Barat, Jawa Tengah, Banten, Sulawesi Tenggara' WHERE nama_bahasa = 'Sunda' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Sunum' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Taa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tabahair (Bipim, Bipin)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tabla' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Tabundung' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Tagalisa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Taliabu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tamakuri' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Barat' WHERE nama_bahasa = 'Taman' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tamario' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tamer Tunai' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Tamuan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Tandia' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tangko' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tapea' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Tarangan Barat' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Tarangan Timur' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tarfia' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tause' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Tengah' WHERE nama_bahasa = 'Tawoyan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tawu Ane' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tebako' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tefanma' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tefaro (Demba)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Tehit' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Tehit Dit (Tehit Tua)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Teiwa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Telaah Babar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Telepe' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Tenggalan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Teon' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Tepin' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Ternate' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Tetun' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tevera Pew' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Tewa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Tidung' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tobati' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku Utara' WHERE nama_bahasa = 'Tobelo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tenggara' WHERE nama_bahasa = 'Tolaki' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Tombatu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tomor' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Barat' WHERE nama_bahasa = 'Topoiyo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Selatan' WHERE nama_bahasa = 'Toraja' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Torweja' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Totoberi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tengah' WHERE nama_bahasa = 'Totoli' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Towe' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Trimuris-Bagusa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Tsaukwambo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Timur' WHERE nama_bahasa = 'Tunjung' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Ulakin (Ulakuno)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Utara' WHERE nama_bahasa = 'Uma Lung' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Una' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Ure (Mere)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Uruangnirin' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Kalimantan', provinsi = 'Kalimantan Barat, Kalimantan Tengah' WHERE nama_bahasa = 'Uud Danum (Ot Danum)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Vamin' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Vedan Nus (Podena)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wabo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Waicen' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wairate (Debra)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Walak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Waliam' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Walsa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wambo Tawe Tirop' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wambon Kenondik (Wombon, Womsi)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Wamesa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Wandamen' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wanggom' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wano' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Wanukaka (Wanokaka)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Warari Onate' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Wardo' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Warembori' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wari' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Warlon' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Warry' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Waruri (Ambumi)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wate' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Wau Arak' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Weinami' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Wemale' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Wersing (Kolana (Wirasina))' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Nusa Tenggara Timur', provinsi = 'Nusa Tenggara Timur' WHERE nama_bahasa = 'Wewewa (Wejewa)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Windesi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wiyagar' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Woda-Woda' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wolani' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Tenggara' WHERE nama_bahasa = 'Wolio' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wombon (Womsi)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wonti (Waropen)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Wooi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Woria' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Sulawesi', provinsi = 'Sulawesi Selatan' WHERE nama_bahasa = 'Wotu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yabanda (Away)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yabega' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Yaben' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yafi' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yaghai Mur' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yaghai Wairu' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Yahadian-Mugim' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yakapis' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Yalahatan' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yali Anggruk' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yali Kosarek' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yali Ninia' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yali Pass Valley' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yamas' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Yamdena' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Yamueti' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Maluku', provinsi = 'Maluku' WHERE nama_bahasa = 'Yatoke' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yaur' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yaur Rihegure' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yawa Onate' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yei' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yei Bawah' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yelmek' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yeresiam' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Yeresiam Kiruru' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Yeresiam Pedalaman (Sirise)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yeretuar (Umare)' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yetfa' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yokari' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yoke' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua' WHERE nama_bahasa = 'Yonggom' AND (wilayah IS NULL OR provinsi IS NULL);
UPDATE bahasa SET wilayah = 'Papua', provinsi = 'Papua Barat' WHERE nama_bahasa = 'Yuafeta' AND (wilayah IS NULL OR provinsi IS NULL);
